name: Publicare Automata Site

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cod
        uses: actions/checkout@v4

      - name: Pregatire Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalare module Python
        run: pip install -r requirements.txt

      - name: Rulare Script AI
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scraper.py

      - name: Instalare Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Descarcare Tema Hugo
        run: git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1

      - name: Construire site
        run: hugo --minify

      - name: Publicare pe internet
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public